# Generated by Django 4.2.3 on 2023-08-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='title',
            new_name='name',
        ),
    ]
